//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alimento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Alimento()
        {
            this.Platillo_Alimento = new HashSet<Platillo_Alimento>();
        }
    
        public int idAlimento { get; set; }
        public string nombre { get; set; }
        public string potasio { get; set; }
        public string hierro { get; set; }
        public string acidoFolico { get; set; }
        public string vitmaminaA { get; set; }
        public string fibra { get; set; }
        public string pesoBruto { get; set; }
        public string pesoNeto { get; set; }
        public string energia { get; set; }
        public string protenia { get; set; }
        public string lipidos { get; set; }
        public string hidratosDC { get; set; }
        public string cargaGlic { get; set; }
        public string indiceGlic { get; set; }
        public string unidad { get; set; }
        public string cantidadSu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Platillo_Alimento> Platillo_Alimento { get; set; }
    }
}
