//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DietaInfo
    {
        public int idInfo { get; set; }
        public Nullable<int> idUsuario { get; set; }
        public string imcInicial { get; set; }
        public string imcActual { get; set; }
        public string peso { get; set; }
        public string altura { get; set; }
        public string naf { get; set; }
        public string resultado { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
