//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanNutri
    {
        public int idPlan { get; set; }
        public Nullable<int> idUsuario { get; set; }
        public string Desayuno { get; set; }
        public string Comida { get; set; }
        public string Cena { get; set; }
        public string Colaciones { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
