//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Platillo_Alimento
    {
        public int idPlatillo_Alimento { get; set; }
        public Nullable<int> idPlatillo { get; set; }
        public Nullable<int> idAlimento { get; set; }
    
        public virtual Alimento Alimento { get; set; }
        public virtual Platillo Platillo { get; set; }
    }
}
