//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PMensaje
    {
        public int idPMensaje { get; set; }
        public Nullable<int> idUsuario { get; set; }
        public Nullable<int> idMedico { get; set; }
        public string mensaje { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual Medico Medico { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
