var hierarchy =
[
    [ "MODEL.Alimento", "class_m_o_d_e_l_1_1_alimento.html", null ],
    [ "CONTROLLER.AlimentosControlador", "class_c_o_n_t_r_o_l_l_e_r_1_1_alimentos_controlador.html", null ],
    [ "MODEL.AlimentosModel", "class_m_o_d_e_l_1_1_alimentos_model.html", null ],
    [ "MODEL.Cita", "class_m_o_d_e_l_1_1_cita.html", null ],
    [ "CONTROLLER.CitaControlador", "class_c_o_n_t_r_o_l_l_e_r_1_1_cita_controlador.html", null ],
    [ "MODEL.CitaModel", "class_m_o_d_e_l_1_1_cita_model.html", null ],
    [ "DbContext", null, [
      [ "MODEL.ProyectoEntities", "class_m_o_d_e_l_1_1_proyecto_entities.html", null ]
    ] ],
    [ "MODEL.DietaInfo", "class_m_o_d_e_l_1_1_dieta_info.html", null ],
    [ "CONTROLLER.DietaInfoControlador", "class_c_o_n_t_r_o_l_l_e_r_1_1_dieta_info_controlador.html", null ],
    [ "MODEL.DietaInfoModel", "class_m_o_d_e_l_1_1_dieta_info_model.html", null ],
    [ "MODEL.Genero", "class_m_o_d_e_l_1_1_genero.html", null ],
    [ "System.Web.UI.MasterPage", null, [
      [ "VIEW.Admin", "class_v_i_e_w_1_1_admin.html", null ],
      [ "VIEW.Master", "class_v_i_e_w_1_1_master.html", null ],
      [ "VIEW.Usuario", "class_v_i_e_w_1_1_usuario.html", null ]
    ] ],
    [ "MODEL.Medico", "class_m_o_d_e_l_1_1_medico.html", null ],
    [ "CONTROLLER.MedicoControlador", "class_c_o_n_t_r_o_l_l_e_r_1_1_medico_controlador.html", null ],
    [ "MODEL.MedicoModel", "class_m_o_d_e_l_1_1_medico_model.html", null ],
    [ "MODEL.Mensaje", "class_m_o_d_e_l_1_1_mensaje.html", null ],
    [ "CONTROLLER.MensajeControlador", "class_c_o_n_t_r_o_l_l_e_r_1_1_mensaje_controlador.html", null ],
    [ "MODEL.MensajeModel", "class_m_o_d_e_l_1_1_mensaje_model.html", null ],
    [ "System.Web.UI.Page", null, [
      [ "VIEW.Control.Alimentos", "class_v_i_e_w_1_1_control_1_1_alimentos.html", null ],
      [ "VIEW.Control.Citas", "class_v_i_e_w_1_1_control_1_1_citas.html", null ],
      [ "VIEW.Control.DietaUsuario", "class_v_i_e_w_1_1_control_1_1_dieta_usuario.html", null ],
      [ "VIEW.Control.Mensajes", "class_v_i_e_w_1_1_control_1_1_mensajes.html", null ],
      [ "VIEW.Control.Platillos", "class_v_i_e_w_1_1_control_1_1_platillos.html", null ],
      [ "VIEW.Control.Usuarios", "class_v_i_e_w_1_1_control_1_1_usuarios.html", null ],
      [ "VIEW.Control.cDashBoard", "class_v_i_e_w_1_1_control_1_1c_dash_board.html", null ],
      [ "VIEW.Inicio", "class_v_i_e_w_1_1_inicio.html", null ],
      [ "VIEW.Login", "class_v_i_e_w_1_1_login.html", null ],
      [ "VIEW.LoginAdmin", "class_v_i_e_w_1_1_login_admin.html", null ],
      [ "VIEW.Registro", "class_v_i_e_w_1_1_registro.html", null ],
      [ "VIEW.Servicios", "class_v_i_e_w_1_1_servicios.html", null ],
      [ "VIEW.User.Citas", "class_v_i_e_w_1_1_user_1_1_citas.html", null ],
      [ "VIEW.User.Plan", "class_v_i_e_w_1_1_user_1_1_plan.html", null ],
      [ "VIEW.User.Platillos", "class_v_i_e_w_1_1_user_1_1_platillos.html", null ],
      [ "VIEW.User.uDashBoard", "class_v_i_e_w_1_1_user_1_1u_dash_board.html", null ],
      [ "VIEW.contacto", "class_v_i_e_w_1_1contacto.html", null ]
    ] ],
    [ "CONTROLLER.PlanControlador", "class_c_o_n_t_r_o_l_l_e_r_1_1_plan_controlador.html", null ],
    [ "MODEL.PlanModel", "class_m_o_d_e_l_1_1_plan_model.html", null ],
    [ "MODEL.PlanNutri", "class_m_o_d_e_l_1_1_plan_nutri.html", null ],
    [ "MODEL.Platillo", "class_m_o_d_e_l_1_1_platillo.html", null ],
    [ "MODEL.Platillo_Alimento", "class_m_o_d_e_l_1_1_platillo___alimento.html", null ],
    [ "CONTROLLER.PlatillosControlador", "class_c_o_n_t_r_o_l_l_e_r_1_1_platillos_controlador.html", null ],
    [ "MODEL.PlatillosModel", "class_m_o_d_e_l_1_1_platillos_model.html", null ],
    [ "MODEL.PMensaje", "class_m_o_d_e_l_1_1_p_mensaje.html", null ],
    [ "MODEL.sysdiagram", "class_m_o_d_e_l_1_1sysdiagram.html", null ],
    [ "MODEL.Usuario", "class_m_o_d_e_l_1_1_usuario.html", null ],
    [ "CONTROLLER.UsuarioControlador", "class_c_o_n_t_r_o_l_l_e_r_1_1_usuario_controlador.html", null ],
    [ "MODEL.UsuarioModel", "class_m_o_d_e_l_1_1_usuario_model.html", null ]
];